# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import smooth_perms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('smooth_perms', '0002_smoothregistrymodel_is_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionadminmixin',
            name='exclude_fields',
            field=models.CharField(blank=True, default='[]', help_text="This fields will be exclude if user doens't have permission given", max_length=1000, null=True, validators=[smooth_perms.validators.validate_tab]),
        ),
        migrations.AlterField(
            model_name='permissionadminmixin',
            name='fields',
            field=models.CharField(blank=True, default='[]', help_text="This fields will be in read-only if user doens't have permission given", max_length=1000, null=True, validators=[smooth_perms.validators.validate_tab]),
        ),
    ]
